apiVersion: v1
kind: ConfigMap
metadata:
    name: garage-config
data:
    DB_HOST: "garage-postgres.canmvttgiwav.us-east-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "garage"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres123"
    SPRING_PROFILES_ACTIVE: "prod"
